# action.yml
name: 'Typilus: Suggest Python Type Annotations with AI (fix)'
description: 'Suggest Likely Python Type Annotations using AI'
branding:
    icon: box
    color: gray-dark
inputs:
  path:
    description: 'File or directory to run Typilus on.'
    required: false
    default: '.'
outputs:
  output:
    description: 'Makes suggeted edits to the pull requests for adding Python Type annotations.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}
